### ISSUE TITLE
Add methods to solve a system of linear equations(using matrices)  [Algebra]

### ISSUE THREAD

**Issue by konthis** [kelork/Python_Project#5]
Would you be interested on adding 2 python programs under the /Algebra folder? I can add 2 methods Gauss' and choleskys, they are entry level algorithms for numerical linear algebra and can be used for multiple purposes, like predicting stock prices etc.

**Comment by kelork** [comment]
I wanted to inform you that I have successfully merged the code implementing the Gauss' and Cholesky's methods into the /Algebra folder. The changes have been incorporated into the main branch.

Feel free to review the merged code, and if you have any feedback or suggestions, please let me know. Your input is highly valued.

Thanks again for your contribution to the project!
